stages:
  - build
  - lint
  - format
  - migrations
  - tests
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${TEST_ENV} .env-test
  script:
    - docker build -t booking_image .

Lint-job:
  stage: lint
  script:
    - docker run --rm --network myNetwork booking_image ruff check

Format-job:
  stage: format
  script:
    - docker run --rm --network myNetwork booking_image ruff format --check

Migrations-job:
  stage: migrations
  script:
    - docker run --rm --network myNetwork booking_image alembic upgrade head

Tests-job:
  stage: tests
  script:
    - docker run --rm --network myNetwork booking_image pytest -s -v

deploy-job:
  stage: deploy
  script:
    - docker compose -f docker-compose-ci.yml up -d
    - docker exec booking_nginx_container nginx -s reload