services:
  booking_back_service:
    container_name: "booking_back_container"
    build:
      context: .
#    ports:
#      - "7777:8000"
    networks:
      - myNetwork
    env_file:
      - .env

  booking_celery_worker_service:
    container_name: "booking_celery_worker_container"
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_application:celery_app worker -l INFO"


  booking_celery_beat_service:
    container_name: "booking_celery_beat_container"
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_application:celery_app beat -l INFO"


networks:
  myNetwork:
    external: true
